name: multilingual_ft
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.18.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==23.1.0
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.3
      - conda-pack==0.6.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - datasets==2.11.0
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - evaluate==0.4.0
      - filelock==3.12.0
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - huggingface-hub==0.14.1
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lightgbm==3.3.5
      - lit==16.0.2
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - networkx==3.1
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pandas==2.0.1
      - pathtools==0.1.2
      - pillow==9.5.0
      - protobuf==4.22.3
      - psutil==5.9.5
      - pyarrow==11.0.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - regex==2023.3.23
      - requests==2.29.0
      - responses==0.18.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentry-sdk==1.21.0
      - seqeval==1.2.2
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==2.0.0
      - tqdm==4.65.0
      - transformers==4.28.1
      - triton==2.0.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.15
      - wandb==0.15.0
      - xgboost==1.4.2
      - xlrd==2.0.1
      - xxhash==3.2.0
      - yarl==1.9.2
prefix: /home/skhanuja/miniconda3/envs/multilingual_ft
